# Generated by Django 2.2.3 on 2019-08-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, unique=True, verbose_name='Order number')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'In progress'), (2, 'Stored'), (3, 'Sent')], verbose_name='Status')),
            ],
        ),
    ]
